

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployments.nifi.name }}
  labels:
    {{- include "Nifi_Kafka.labels" . | nindent 4 }}
    app: {{ .Values.deployments.nifi.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "Nifi_Kafka.selectorLabels" . | nindent 6 }}
      app: {{ .Values.deployments.nifi.name }}
  template:
    metadata:
      labels:
        {{- include "Nifi_Kafka.labels" . | nindent 8 }}
        app: {{ .Values.deployments.nifi.name }}
    spec:
      containers:
        - image: {{ .Values.image.registry }}/{{ .Values.deployments.nifi.image }}:{{ .Values.deployments.nifi.tag}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: nifi
          ports:
            - containerPort: {{ .Values.deployments.nifi.containerPort}}
          {{- include "Nifi.enviroments" . | nindent 10 }}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nifi-v2
  labels:
    app: nifi-version-2
    name: test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nifi-version-2
      name: test
  template:
    metadata:
      labels:
        app: nifi-version-2
        name: test
    spec:
      containers:
        - env:
          - name: NIFI_WEB_HTTP_PORT
            value: "8090"
          image: harbor.sharing.ncc.local/ncfc/nifi:latest
          name: nifi
          ports:
            - containerPort: 8090
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "Nifi_Kafka.labels" . | nindent 4 }}
    app:  {{ .Values.deployments.kafdrop.name }}
  name: {{ .Values.deployments.kafdrop.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "Nifi_Kafka.labels" . | nindent 6 }}
      app:  {{ .Values.deployments.kafdrop.name }}
  template:
    metadata:
      labels:
        {{- include "Nifi_Kafka.labels" . | nindent 8 }}
        app:  {{ .Values.deployments.kafdrop.name }}
    spec:
      containers:
        {{- include "Kafdrop.enviroments" . | nindent 8 }}
          image: {{ .Values.image.registry }}/{{ .Values.deployments.kafdrop.image }}:{{ .Values.deployments.kafdrop.tag}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: kafdrop
          ports:
            - containerPort: {{ .Values.deployments.kafdrop.containerPort}}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}


