apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.nifi.name }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: {{ .Values.ingress.nifi.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name.nifi }}
                port:
                  number: {{ .Values.ingress.nifi.port }}

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nifi-v2-kafka-test-helm
spec:
  ingressClassName: nginx
  rules:
    - host: nifi.v2.sharing.ncc.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nifi-v2-service
                port:
                  number: 8090


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.kafdrop.name }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.kafdrop.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.service.name.kafdrop }}
                port:
                  number: {{ .Values.ingress.kafdrop.port }}
