apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "Nifi_Kafka.labels" . | nindent 4 }}
  name: {{ .Values.service.name.zookeeper }}
spec:
  type: {{ .Values.service.type }}
  ports:
      - port: {{ .Values.service.ports.zookeeper.port }}
        protocol: "TCP"
        targetPort: {{ .Values.service.ports.zookeeper.port }}
  selector:
    {{- include "Nifi_Kafka.selectorLabels" . | nindent 6 }}
      app: {{ .Values.deployments.zookeeper.name }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "Nifi_Kafka.labels" . | nindent 4 }}
  name: {{ .Values.service.name.kafka }}
spec:
  type:  {{ .Values.service.type }}
  ports:
      - port: {{ .Values.service.ports.kafka.portBroker }}
        protocol: "TCP"
        targetPort: {{ .Values.service.ports.kafka.portBroker }}
  selector:
    {{- include "Nifi_Kafka.selectorLabels" . | nindent 6 }}
      app: {{ .Values.deployments.kafka.name }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "Nifi_Kafka.labels" . | nindent 4 }}
  name: {{ .Values.service.name.nifi }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.nifi.port }}
      protocol: "TCP"
  selector:
    {{- include "Nifi_Kafka.selectorLabels" . | nindent 6 }}
      app: {{ .Values.deployments.nifi.name }}


---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nifi-version-2
    name: test
  name: nifi-v2-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.nifi.port2 }}
      protocol: "TCP"
  selector:
    app: nifi-version-2
    name: test


---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "Nifi_Kafka.labels" . | nindent 4 }}
    app: {{ .Values.service.name.kafdrop }}
  name: {{ .Values.service.name.kafdrop }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.kafdrop.port }}
      targetPort: {{ .Values.service.ports.kafdrop.port }}
  selector:
    app: {{ .Values.deployments.kafdrop.name }}
