apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.deployments.zookeeper.name }}
  labels:
    {{- include "Nifi_Kafka.labels" . | nindent 4 }}
    app: {{ .Values.deployments.zookeeper.name }}
spec:
  serviceName: {{ .Values.service.name.zookeeper }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "Nifi_Kafka.selectorLabels" . | nindent 6 }}
      app: {{ .Values.deployments.zookeeper.name }}
  template:
    metadata:
      labels:
        {{- include "Nifi_Kafka.labels" . | nindent 8 }}
        app: {{ .Values.deployments.zookeeper.name }}
    spec:
      containers:
        {{- include "Zookeeper.enviroments" . | nindent 8 }}
          image: {{ .Values.image.registry }}/{{ .Values.deployments.zookeeper.image }}:{{ .Values.deployments.zookeeper.tag}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: zookeeper
          ports:
            - containerPort: {{ .Values.deployments.zookeeper.containerPort}}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.deployments.kafka.name }}
  labels:
    {{- include "Nifi_Kafka.labels" . | nindent 4 }}
    app: {{ .Values.deployments.kafka.name }}
spec:
  serviceName: {{ .Values.service.name.kafka }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "Nifi_Kafka.selectorLabels" . | nindent 6 }}
      app: {{ .Values.deployments.kafka.name }}
  template:
    metadata:
      labels:
        {{- include "Nifi_Kafka.labels" . | nindent 8 }}
        app: {{ .Values.deployments.kafka.name }}
    spec:
      containers:
        {{- include "Kafka.enviroments" . | nindent 8 }}
          image: {{ .Values.image.registry }}/{{ .Values.deployments.kafka.image }}:{{ .Values.deployments.kafka.tag}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: kafka-broker
          ports:
            - containerPort: {{ .Values.deployments.kafka.containerPort}}
      {{- if .Values.image.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.image.imagePullSecrets | indent 8 }}
      {{- end }}
