service:
  type: ClusterIP
  name:
    zookeeper: zookeeper-service
    kafka: kafka-service
    nifi: nifi-service
    kafdrop: kafdrop-service
  labels:
    zookeeper: zookeeper-service
    kafka: kafka-service
    nifi: nifi-service
  ports:
    zookeeper:
      port: 2181
      nodePort: 30181
    kafka:
      portBroker: 9092
      nameBroker: kafka-broker
      portHost: 9094
      nameHost: kafka-host
      portCtrl: 9094
      nameCtrl: kafka-ctrl
    nifi:
      port: 8080
      port2: 8090
    kafdrop:
      port: 9000

deployments:
  nifi:
    name: dep-nifi
    image: ncfc/nifi
    tag: "latest"
    containerPort: 8080

  kafka:
    name: dep-kafka
    image: ncfc/kafka
    tag: "latest"
    containerPort: 9092

  zookeeper:
    name: dep-zookeeper
    image: ncfc/zookeeper
    tag: "latest"
    containerPort: 2181

  kafdrop:
    name: dep-kafdrop
    image: ncfc/kafdrop
    tag: "latest"
    containerPort: 9000

replicaCount: 1
image:
  registry: harbor.sharing.ncc.local
  imagePullSecrets:
    - name: "regcred"
  pullPolicy: IfNotPresent
ingress:
  secret: ingress-cert
  ingressClassName: nginx
  nifi:
    name: nifi-kafka-test-helm
    host: nifi.sharing.ncc.local
    port: 8080

  kafdrop:
    name: kafdrop-ingress
    host: kafdrop.sharing.ncc.local
    port: 9000
